@startuml
' Modelo de domínio do sistema: Entrega 1.
'
' Este arquivo é o ponto de partida. Substitua pelo modelo da sua equipe.
' O diagrama precisa corresponder ao código entregue.
'
' Para gerar a imagem: instale o plugin PlantUML no IntelliJ, ou use
'   plantuml docs/modelo.puml
' e versione a imagem gerada ao lado deste arquivo.

skinparam classAttributeIconSize 0
hide empty members

class Item {
  - codigo : String
  - titulo : String
  - teste: teste1
}

class Exemplar {
  - tombo : String
}

class Usuario {
  - matricula : String
  - nome : String
}

class Emprestimo {
  - titulo : String
  - status : Boolean
}

Item "1" *-- "0..*" Exemplar : possui
Exemplar "1" *-- "0..*" Emprestimo : possui
Emprestimo "1" *-- "0..*" Usuario : possui


@enduml
